image: python:3.6.4-alpine3.7@sha256:10bd7a59cfac2a784bedd1e6d89887995559f00b61f005a101845ed736bed779

pages:
  script:
  - apk --no-cache add build-base python-dev jpeg-dev zlib-dev graphviz ttf-freefont
  - pip install Pillow sphinx
  - pip install recommonmark sphinxcontrib-blockdiag sphinxcontrib-actdiag sphinxcontrib-excel-table 
  - pip install sphinxcontrib-nwdiag sphinxcontrib-plantuml sphinxcontrib-seqdiag sphinx_rtd_theme
  - apk --no-cache add make
  - make html
  - mv _build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
